apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8qr0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8qr0
    app.kubernetes.io/part-of: ci1t-830-0057-app
  name: devfile-sample-8qr0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8qr0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8qr0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0057-tenant/ci1t-830-0057-app/devfile-sample-8qr0@sha256:746930ce10d9ecbeed261403b7bd417292234794dec7db11f286511b352ba431
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
